### PR TITLE
Ahb

### PR DESCRIPTION
**Pull request by terpstra**
TileLink to AHB Bridge

### CODE REVIEW

**Comment by mwachs5** [comment]
Is this AHB or AHB-Lite? I mean, does it depend on any of the functionality
that is not in Lite?

On Monday, May 16, 2016, Wesley W. Terpstra <notifications@github.com>
wrote:

> TileLink to AHB Bridge
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ucb-bar/uncore/pull/42
> Commit Summary
>
>    - ahb: syntactically correct first version (missing Put fragmentation)
>    - ahb: handle fragmented puts
>    - ahb: amoalu does not need so many parameters! (i want to reuse it)
>    - ahb: flip IOs, wrap Modules, case defaults, AMOALU parameters
>    - ahb: fixed a few bugs by final pre-testing visual inspection
>    - ahb: rename hreadyout => hready (other cores use this name)
>    - ahb: testing revealed two bugs
>
> File Changes
>
>    - *A* src/main/scala/ahb.scala
>    <https://github.com/ucb-bar/uncore/pull/42/files#diff-0> (449)
>    - *M* src/main/scala/amoalu.scala
>    <https://github.com/ucb-bar/uncore/pull/42/files#diff-1> (3)
>
> Patch Links:
>
>    - https://github.com/ucb-bar/uncore/pull/42.patch
>    - https://github.com/ucb-bar/uncore/pull/42.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ucb-bar/uncore/pull/42>
>


-- 
Megan A. Wachs
Engineer | SiFive, Inc
300 Brannan St, Suite 403
San Francisco, CA  94107
megan@sifive.com

**Comment by zhemao** [comment]
Yeah, is there a reason this isn't using the AHB-Lite-compatible HASTI bundles already in junctions?

**Comment by terpstra** [comment]
It is AHB-Lite.

I did not know HASTI existed until yesterday. Looking at hasti.scala, I
think I can refactor it to use the same bundles. hasti is missing the hprot
definitions, so would need to be updated first. What is the policy on which
submodules can depend on each other? It depends on AMOALU and TileLink from
uncore, so I am guessing I cannot simply put it into the hasti folder.

**Comment by mwachs5** [comment]
If it's AHB-Lite, convention in the world seems to call it AHBL. Also may be worth noting the version of the AMBA spec it corresponds to (even if there is only v3 for AHB, I'm not even sure).

**Comment by zhemao** [comment]
You should put the converter in the uncore module, but import the HASTI bundle definitions from junctions. If there's a missing field, just add it to the definition in junctions and make a separate pull request. Also, I would highly prefer you add a unit test in groundtest for this converter if it's not being used in the default RocketChip configuration. Take a look at the test for the existing AXI -> AHB (NASTI -> HASTI) converter.

**Comment by terpstra** [comment]
This must be merged concurrently with the ahb pull requests on rocket-chip and junctions

**Comment by aswaterman** [comment]
lgtm

**Pull request merged**
