### PR TITLE
Add L2 VLS, with support for 1 segment

### PR DESCRIPTION
**Pull request by albert-magyar**
Not necessarily trying to merge this as is, but I'd like to see how I could move to upstreaming VLS. There's also a corresponding branch for rocket-chip with the appropriate parameters in configs and the AXI hookups for VLS configuration, but I'm certainly happy to clean things up in my uncore changes first. Otherwise, I could open a pull request for rocket-chip too.

### CODE REVIEW

**Comment by zhemao** [comment]
I think we should set aside some time to talk about what the changes are here and how to go about merging. When are you free this week?

**Comment by aswaterman** [comment]
We can talk about it at the rocket-dev meeting Monday.

**Comment by hcook** [comment]
I have a few concrete suggestions for the uncore stuff alone, see below. We'll discuss the rocket-chip strategy at the meeting, but the short story is we want to try to keep VLS on its own rocket-chip/vls branch for now, while still merging the building blocks into uncore/master. Pragmatically, this means trying to keep references to VLS-specific parameters off of the dynamic execution of mainline L2Cache for now. The following suggestions should resolve things in that direction:

- [ ] `MetadataArray` and `SplitMetadataArray` should be remerged into a single class called `MetaDataArray`, which uses the `cde.Field` `SplitMetadata` to choose the internal organization. `SplitMetadata` should be included alongside the other cache parameters in cache.scala, given a `val` in `HasCacheParameters`, and defined in rocket-chip/master. I think this is a good idea because in addition to reducing code duplication, there are potentially use cases other than VLS (e.g. way prediction) that could use the split structure, so seems worth parameterizing independently. Maybe even make this a separate pull request?
- [ ] Conversely, I want to see separate `L2MetadataArray` and `L2MetadataArrayWithVLS` classes, the former of which makes no reference to any VLS parameters other than `SplitMetadata`. Same for  `L2HellaCacheBank` and `L2MetaRWIO`. You could just copy the code for each over to vls.scala for starters. Ideally I think you could get some code reuse for the former out of an abstract base class (`L2MetadataArrayLike`?) with e.g. functions that can be filled in for `s1_tag_match_way` and `replace_way`, and then concrete subclasses that implement each, but I suspect defining the io type is going to lead to some annoyance...
- [ ] With `L2HellaCacheBankWithVLS` in hand, specialize `BuildL2CoherenceManager` in Config `WithVLS`, i.e. instead of using `UseVLS` inside `L2HellaCacheBank`
- [ ] You can still use `UseVLS` inside of RocketChip.scala, but we're going to keep it on its own branch.

Ok, so hopefully it's clear that in one case we're promoting `SplitMetadata` to mainline rocket-chip usage and in the other case we're trying to keep from even having to admit that `UseVLS` exists. I know this is a bit onerous but I think it is the best compromise along the lines of what we did for Boom and Hwacha.

I have a few followup questions as well:

- I assume you want any VLS allocation evenly striped across all banks? Is it worth trying to support Configurations where not all banks use VLS? 
- It would be good to have a spec for how gconf and lconf are used. Is there a way to use the uncore SCRs instead? What's the plan for multiple segments?

Let me know what you think. We'll discuss in more detail on Monday and I can meet with you before then too.

**Comment by albert-magyar** [comment]
Even though that's kind of the opposite of how the code is now, that definitely makes sense. The push to mainline VLS was mostly to ease the git-fu for the Hurricane tapeout merges. Way selection certainly seems like a generally useful feature, too.

Those all seem like fairly easy changes to make, so I'll go ahead and reorganize it to make SplitMetadata an independent parameter that's always available.

- I thought about per-bank configuration, since it has the potential to reduce the granularity of allocation. The reason I didn't add this was that the address fields (bank bits less significant than index bits) don't work for contiguous VLS allocations that span all sets but don't span all banks.
- Agreed about the spec; I'll look at the uncore SCRs.
- The issue with multiple segments is a more general problem: replacement of hardware-managed ways isn't as effective with VLS allocations active. I think having entirely separate code for the `L2MetadataArrayWithVLS` will make it easier to come up with a clean solution (clamping values of internal nodes in a PLRU tree, etc.) that the current version, which tries to keep the delta in `L2MetadataArray` as small as possible.

**Comment by albert-magyar** [comment]
I split the split metadata into ucb-bar/uncore#14

**Pull request closed without merging**
